name: Daily Python Script

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Set this to your required Python version

      - name: Install dependencies
        run: |
          pip install python-telegram-bot requests beautifulsoup4  # Replace with your dependencies installation command

      - name: Run script
        run: python houses.py  # Replace with the path to your Python script
